### ISSUE TITLE
Endpoints API: Pass limit query parameter

### ISSUE THREAD

**Issue by ManAnRuck** [OParl/dev-website#257]
When a `limit` is set to the endpoint api, the `next` metadata do not pass this limit.

Reproduce:
1. open https://dev.oparl.org/api/endpoints?limit=1&page=2
2. check/open `meta.next`
3. content of next url is empty

Expected behaviour:
pass limit to meta.next value

**Comment by eFrane** [comment]
@ManAnRuck Thank your for reporting this bug!

`meta.next` links always contain the `limit` now. I also added `self` links.

**Comment by ManAnRuck** [comment]
@eFrane thank you for this very fast fix! 🤗

**Comment by ManAnRuck** [comment]
@eFrane I think there is still an issue.

there are only 25 results when I open https://dev.oparl.org/api/endpoints
there is no next url. 
but when I open https://dev.oparl.org/api/endpoints?page=2&limit=25 there are more results.
on the second page is also some difference in data structure.

instead of an data array there is a data object.

https://dev.oparl.org/api/endpoints
<img width="520" alt="Bildschirmfoto 2020-04-20 um 19 14 15" src="https://user-images.githubusercontent.com/2183135/79779761-2aa53280-833b-11ea-8a07-791bea3a5764.png">
<img width="394" alt="Bildschirmfoto 2020-04-20 um 19 14 09" src="https://user-images.githubusercontent.com/2183135/79779767-2d078c80-833b-11ea-8655-7aca7f715398.png">



https://dev.oparl.org/api/endpoints?page=2&limit=25
<img width="790" alt="Bildschirmfoto 2020-04-20 um 19 13 05" src="https://user-images.githubusercontent.com/2183135/79779657-034e6580-833b-11ea-8b6a-60423127b7d4.png">

**Comment by eFrane** [comment]
Okay fine, I'll write an integration test this time. 🙈 

That does look weird indeed. Will hopefully be just as easy to fix.

**Comment by eFrane** [comment]
The issue is fixed, but I'm busy fighting a fight against Travis having a different opinion on the test suite than my local machine.

**Comment by eFrane** [comment]
Fixed in the live system.

**Comment by ManAnRuck** [comment]
@eFrane sorry 😇 I still see an issue with the limit & pagination.

when I open https://dev.oparl.org/api/endpoints?page=1&limit=25 there is the next value `null` but when I open https://dev.oparl.org/api/endpoints?page=2&limit=25 there are more data

**Comment by eFrane** [comment]
This keeps haunting me.

**Comment by eFrane** [comment]
Fixed. I keep having to thank you for being so diligent to get this API call to be actually correct. I put this together about a million years ago and it sort worked for me. I feel like we're getting close to it actually working. 🙈 

A heads-up though: I plan on migrating this api to the json:api format soonish. Since you seem to be the only active user, let me know if your use case can handle being suddenly broken or if I should keep the old formatting around for a little while then.

**Comment by ManAnRuck** [comment]
Thank you :) now it works :)

sounds great. thanks my planned micro services I want to use, it's not a big issue when there is a change ;) then I can test my error reporter which should highlight it 😅
